# Define per-form-type expectations.
# You can extend this file with all your real fields and per-field validations.
form_types:
  quote_stub:
    required_fields: ["repair_advice", "material_code", "specification", "quantity", "hours_estimate"]
    numeric_min:
      quantity: 0.0
      hours_estimate: 0.0
    min_length:
      repair_advice: 5
    aliases: {}   # add synonyms if your CSV/PDF uses different names

  service_report:
    # Example expectations for the full service PDF extraction (once you parse it into JSON)
    required_fields: ["arrival_time", "departure_time", "total_hours", "attributes_complete"]
    bool_expected_true: ["attributes_complete"]
    url_fields:
      - field: "video_link"
        contains_any: ["sharepoint"]
    cross_checks:
      - if_true: "materials_used"
        then_required: ["materials_booked_order_id"]
      - if_true: "major_fault"
        then_required: ["tech_support_consulted"]